services:
  nginx:
    image: nginx:alpine3.22
    container_name: nginx_cont
    working_dir: /var/www/html
    volumes:
      - ./php/:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php
    restart: always
    
  php:
    build:
      context: .
    #command: ["sh","-c","docker-php-ext-install mysqli && exec php-fpm"]
    container_name: php_cont
    working_dir: /var/www/html
    volumes:
      - ./php/:/var/www/html
    depends_on:
      - db
    restart: always
    
  db: 
    image: mysql
    container_name: mysql_cont
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: crud
    volumes:
       - ./php/crud.sql:/docker-entrypoint-initdb.d/crud.sql
    ports:
      - 3306:3306
  
    

    
    
